# Quantum PK/PD Configuration

# Data paths
data:
  input_file: "data/EstData.csv"
  output_dir: "results/"
  
# Clinical trial parameters
clinical:
  biomarker_threshold: 3.3  # ng/mL
  target_suppression_primary: 0.90  # 90% of subjects
  target_suppression_secondary: 0.75  # 75% of subjects
  dose_increment_daily: 0.5  # mg
  dose_increment_weekly: 5  # mg
  dosing_interval_daily: 24  # hours
  dosing_interval_weekly: 168  # hours
  
# Population parameters
population:
  baseline_weight_range: [50, 100]  # kg
  extended_weight_range: [70, 140]  # kg
  
# Model parameters
modeling:
  compartments: [1, 2]  # Test both 1 and 2 compartment models
  absorption_types: ["first_order", "zero_order"]
  elimination_types: ["linear", "nonlinear"]
  pd_response_types: ["direct", "indirect"]
  
# nlmixr2 parameters
nlmixr2:
  estimation_methods: ["saem", "focei", "foce"]
  control:
    print: 1
    maxInnerIterations: 300
    maxOuterIterations: 1000
  vpc:
    n_sim: 1000
    pi: [0.05, 0.95]
    ci: [0.05, 0.95]
  
# PennyLane Quantum parameters
quantum:
  device: "default.qubit"
  device_wires: 16
  shots: 1024
  max_iterations: 100
  differentiable: true
  
# PennyLane specific settings
pennylane:
  optimizer: "AdamOptimizer"
  learning_rate: 0.01
  templates:
    - "BasicEntanglerLayers"
    - "StronglyEntanglingLayers" 
    - "SimplifiedTwoDesign"
  
# ZX Calculus settings for tensor networks
zx_calculus:
  backend: "pyzx"
  simplification_level: "full"
  optimization: true
  circuit_extraction: true
  
# Optimization parameters
optimization:
  method: "bayesian"
  n_trials: 100
  timeout: 3600  # seconds
  
# Simulation parameters
simulation:
  n_subjects: 1000
  n_replicates: 100
  steady_state_threshold: 0.95